### ISSUE TITLE
unable to install this pod

### ISSUE THREAD

**Issue by mrramdhas** [Automattic/Gridicons-iOS#40]
Facing error message while installing the pod. 

  pod 'Gridicons', :podspec => 'https://raw.github.com/Automattic/Gridicons-iOS/develop/Gridicons.podspec'

Error:"

!] Error installing Gridicons
[!] /usr/local/bin/git clone https://github.com/Automattic/Gridicons-iOS.git /var/folders/d6/f8rr51jj0xg047d_r6lkjjnm0000gn/T/d20190212-51692-kw14m9 --template= --single-branch --depth 1 --branch 0.18

Cloning into '/var/folders/d6/f8rr51jj0xg047d_r6lkjjnm0000gn/T/d20190212-51692-kw14m9'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by mindgraffiti** [comment]
Hello @mrramdhas 👋 

That looks like a git cloning issue, not a Gridicons issue. Please check out [this GitHub troubleshooting article](https://help.github.com/en/github/authenticating-to-github/error-permission-denied-publickey).

As this is not related to the Gridicons pod itself, I will close this issue.
